@startuml diagrama

class Usuario
class Foco{
    -EstadoFoco Estado
    + Encender ()
    + Apagar ()
    + Estado ()
}
class EstadoFoco

Usuario o-- Foco
Foco *-- EstadoFoco
EstadoFoco --|> bool
@enduml
